### ISSUE TITLE
Allow multiple responder certificates in OCSP response

### ISSUE THREAD

**Issue by timukasr** [web-eid/web-eid-authtoken-validation-java#28]
Some OCSP servers (e.g. http://ocsp.eparaksts.lv) add multiple responder certificates in OCSP response. This causes auth token validation error:
`User certificate revocation check has failed: OCSP response must contain one responder certificate, received 2 certificates instead`
due to this check:
https://github.com/web-eid/web-eid-authtoken-validation-java/blob/main/src/main/java/eu/webeid/security/validator/certvalidators/SubjectCertificateNotRevokedValidator.java#L142-L145

Is it possible to modify the check so that if at least one responder certificate is valid, then whole response is valid?

**Comment by mrts** [comment]
Thank you for the suggestion! Yes, we will modify the check as soon as possible.

**Comment by mrts** [comment]
A new pre-release version `2.0.1-SNAPSHOT` has been published with the fix. The pull request is https://github.com/web-eid/web-eid-authtoken-validation-java/pull/29. It also contains dependency updates and minor refactoring.

Can you please test it? Also, can you perhaps provide an example Latvian EID Web eID authentication token that uses the http://ocsp.eparaksts.lv/ OCSP server, along with the corresponding issuer certificate?

**Comment by timukasr** [comment]
Thank you, OCSP part seems to working now.

Issue occurred with end user, so I cannot share their authentication token/certificate. For similar reasons, I cannot test the full authentication token validation yet.

**Comment by mrts** [comment]
Thank you for verifying! Understood, sharing the token would leak personal details. 

I will publish the release version `2.0.1` with the fix soon.
