### ISSUE TITLE
Please consider removing guava as a dependency

### ISSUE THREAD

**Issue by tenor-dev** [web-eid/web-eid-authtoken-validation-java#32]
Guava is a huge library and bringing it as a dependency to just use 3 simple functions is not a good practice.

**Comment by mrts** [comment]
Agreed, we ended up using Guava less than we initially expected so it can be removed.

Generally using libraries like Guava or Apache Commons is a good practice as they are battle-tested and have solid thread-safety guarantees.

**Comment by mrts** [comment]
This is now implemented in #34. Can you please review the pull request? Note that it is based on #33, I will rebase it on top of main after #33 is merged.

**Comment by tenor-dev** [comment]
@mrts thanks a lot!
