### ISSUE TITLE
Publish source jar in Maven repository

### ISSUE THREAD

**Issue by alarkvell** [web-eid/web-eid-authtoken-validation-java#37]
https://gitlab.com/web-eid/service/web-eid-authtoken-validation-java/-/packages/10019924 doesn't seem to contain sources jar. Please publish sources jar (and possibly also javadoc jar) alongside the release artifact, it's a common practice (e.g. https://repo1.maven.org/maven2/org/springframework/spring-webmvc/5.3.23/). Then IDE-s could fetch it automatically and make browsing and debugging the source code easier, when `authtoken-validation` is used as a dependency in some project.

**Comment by mrts** [comment]
Thank you, good point! We will publish both the source and Javadoc JARs as soon as possible.

**Comment by mrts** [comment]
Unfortunately, the timeline for publishing the source and Javadoc JARs in the central Maven repository is not within the direct control of our development team, as we currently do not have access to the official Sonatype Maven Central account. @kristelmerilain will make an announcement as soon as we are able to proceed with the publication.

Would it help if we publish the source and Javadoc JARs in the [GitLab package repository](https://gitlab.com/web-eid/service/web-eid-authtoken-validation-java/-/packages)?

**Comment by alarkvell** [comment]
In my opinion it would be helpful if the source and Javadoc JARs would be published alongside the release artifact (currently in GitLab package repository). Publishing in Maven Central could be considered a separate topic.

**Comment by mrts** [comment]
Thanks, indeed, you are right, my previous message unduly shifted focus to the constraints regarding Maven Central publication. I'm pleased to inform you that we will publish the source and Javadoc JARs alongside the release artifact in the GitLab package repository when version 3.0.1 is released.

**Comment by mrts** [comment]
Version 3.0.1 is now released and source and Javadoc JARs are [available in GitLab package repository](https://gitlab.com/web-eid/service/web-eid-authtoken-validation-java/-/packages/20593180).
