### ISSUE TITLE
Refactor trusted CA finding in SubjectCertificateTrustedValidator

### ISSUE THREAD

**Issue by mrts** [web-eid/web-eid-authtoken-validation-java#5]
Use standard JCE PKIX classes for certificate trust validation in `SubjectCertificateTrustedValidator.validateCertificateTrusted()`.

**Comment by metsma** [comment]
Sry wrong button.
Make sure you check SKI and AKI matching and also signature. Subject name matching is not good enough

**Comment by mrts** [comment]
Thanks! Sure, first step is lookup, second step is still signature verification. I'll submit the PR soon, then you can see it better.
